baseURL = '/'
languageCode = 'ca_ES'
title = 'cnsld.cc'
theme = 'smol'

[caches]
  [caches.images]
    dir = ':cacheDir/images'

[markup.goldmark.renderer]
unsafe= true

[permalinks]
posts = "/blog/:year/:title/"

[[module.mounts]]
source = 'static'
target = 'static'

[[module.mounts]]
source = 'images'
target = 'static/images'

[pagination]
  disableAliases = false
  pagerSize = 100
  path = 'page'

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "Now"
url = "/now"
weight = 2

[languages.ca]
  weight = 1
  [languages.ca.params.formats.date]
    long = "2 de January de 2006"