baseURL = '/'
defaultContentLanguage = 'ca'
languageCode = 'ca'
title = 'cnsld.cc'
theme = 'smol'

[caches]
  [caches.images]
    dir = ':cacheDir/images'

[markup.goldmark.renderer]
unsafe= true

[[module.mounts]]
source = 'static'
target = 'static'

[[module.mounts]]
source = 'images'
target = 'static/images'

[pagination]
  disableAliases = false
  pagerSize = 100
  path = 'page'

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "Slash"
url = "/slash"
weight = 2
